---
apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdEnvironment
metadata:
  name: env-debugger
spec:
  targetNamespace: debugger
  providers:
    iqe:
      # Base image for iqe-tests
      imageBase: "quay.io/cloudservices/iqe-tests"
      # Level of access this pod has in the namespace
      k8sAccessLevel: edit
      # gather configuraiton for the specified environment
      configAccess: environment
    web:
      port: 8000
      mode: operator
    metrics:
      port: 9000
      mode: operator
      path: "/metrics"
    kafka:
      namespace: default
      clusterName: crc-cluster
      mode: local 
    db:
      imageList: 
      - version: 10
        image: quay.io/cloudservices/postgresql-rds:10-1
      - version: 12
        image: quay.io/cloudservices/postgresql-rds:12-1
      mode: local
    logging:
      mode: none
    objectStore:
      mode: minio
      port: 9000
    inMemoryDb:
      mode: redis
  resourceDefaults:
    limits: 
      cpu: "500m"
      memory: "8192Mi"
    requests:
      cpu: "300m"
      memory: "1024Mi"
