envName: env-debugger
apps:
- name: host-inventory
  host: local
  repo: /home/bholifie/git/insights-host-inventory/
  path: deployment.yaml
  parameters:
    # IMAGE: 192.168.39.77:5000/host-inventory
    IMAGE: 127.0.0.1:5000/host-inventory
    CLOWDER_ENABLED: "true" 
