---
apiVersion: v1
kind: Pod
metadata:
  name: django-unit-db
spec:
  imagePullSecrets:
    - name: quay-cloudservices-pull
  containers:
    - name: djano-unit-db
      image: "quay.io/cloudservices/postgresql-rds:12-1"
      livenessProbe:
        exec:
          command:
            - psql
            - '-U'
            - $(POSTGRESQL_USER)
            - '-d'
            - $(POSTGRESQL_DATABASE)
            - '-c'
            - SELECT 1
        initialDelaySeconds: 15
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      imagePullPolicy: Always
      restartPolicy: always
      ports:
        - name: djano-unit-db
          containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRESQL_USER
          value: insights
        - name: POSTGRESQL_PASSWORD
          vale: insights
        - name: POSTGRESQL_DATABASE
          value: insights
      volumeMounts:
        - name: django-unit-db
          mountPath: /var/lib/pgsql/data
  volumes:
    - name: django-unit-db
      emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: django-unit-db
  labels:
    app: inventory
    service: db
spec:
  ports:
    - name: django-unit-db
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: inventory
    service: db
